import Foundation

class TaskTimeEstimator {
    let timeEstimates: [String: Int] = [
        "email": 10,
        "groceries": 20,
        "presentation": 45,
        "reading": 30,
        "cleaning": 60,
        "writing": 90,
        "planning": 120,
        "workout": 50,
        "cooking": 40,
        "laundry": 70,
        "meetings": 60,
        "coding": 150,
        "commuting": 30,
        "shopping": 45,
        "walking the dog": 30,
        "fixing": 50,
        "painting": 120,
        "decorating": 85,
        "reviewing documents": 35,
        "social media": 15,
        "watching TV": 120,
        "studying": 120,
        "research": 60,
        "drawing": 45,
        "sewing": 90,
        "baking": 120,
        "photography": 90,
        "cleaning garage": 120,
        "vehicle maintenance": 90,
        "budgeting": 50,
        "packing": 60,
        "moving furniture": 75,
        "assembling furniture": 90,
        "meditation": 30,
        "yoga": 60,
        "running": 30,
        "biking": 45,
        "swimming": 60,
        "haircut": 45,
        "doctor appointment": 60,
        "dental checkup": 45,
        "banking": 20,
        "paying bills": 15,
        "making calls": 20,
        "appointment setting": 10,
        "car washing": 30,
        "video gaming": 120,
        "pet grooming": 60,
        "vaccuuming": 30,
        "mopping": 20,
        "recycling": 25,
        "trashing out": 15,
        "filing taxes": 120,
        "insurance review": 40,
        "house repairs": 120,
        "online shopping": 30,
        "socializing": 180,
        "movie watching": 120,
        "music practice": 60,
        "concert going": 180,
        "beach outing": 240,
        "hiking": 180,
        "skiing": 240,
        "snowboarding": 240,
        "camping": 480,
        "road trip": 360,
        "flight travel": 240,
        "reading emails": 15,
        "updating software": 25,
        "attending webinar": 60,
        "taking a nap": 90,
        "washing dishes": 30,
        "taking a shower": 20,
        "watching a tutorial": 45,
        "organizing workspace": 30,
        "brewing coffee": 15,
        "checking mail": 10,
        "journaling": 25,
        "listening to a podcast": 60,
        "exercising": 60,
        "practicing guitar": 45,
        "knitting": 60,
        "scrapbooking": 90,
        "bird watching": 60,
        "solving a puzzle": 90,
        "playing chess": 30,
        "brewing beer": 240,
        "wine tasting": 120,
        "attending a play": 150,
        "visiting a museum": 180,
        "going to the zoo": 180,
        "attending a dance class": 60,
        "singing practice": 60,
        "going to the cinema": 150,
        "dinner cooking": 60,
        "making breakfast": 30,
        "preparing lunch": 45,
        "editing videos": 120,
        "photo editing": 60,
        "gardening": 120,
        "fishing": 240,
        "kayaking": 180,
        "surfing": 120,
        "snorkeling": 90,
        "scuba diving": 180,
        "skydiving": 240,
        "mountain climbing": 480,
        "learning a new language": 45,
        "tutoring": 60,
        "mentoring": 90,
        "volunteering": 120,
        "fundraising": 180,
        "networking event": 120,
        "family game night": 180,
        "doing a crossword": 30,
        "playing video games": 120,
        "chatting with friends": 90,
        "lunch with colleagues": 60,
        "coffee with a friend": 45,
        "date night": 180,
        "pilates": 60,
        "spinning class": 45,
        "kickboxing": 60,
        "martial arts": 90,
        "archery": 60,
        "horseback riding": 120,
        "safari tour": 360,
        "antique hunting": 120,
        "thrifting": 90,
        "live music": 180,
        "opera": 180,
        "ballet": 180,
        "art class": 120,
        "cooking class": 90,
        "wine making": 480,
        "cheese making": 240,
        "home brewing": 360,
        "pottery": 120,
        "street photography": 180,
        "landscape painting": 240,
        "writing poetry": 60,
        "writing a short story": 180,
        "novel writing": 360,
        "comic book creation": 120,
        "board game designing": 240,
        "role-playing games": 240,
        "collecting": 60,
        "stamp collecting": 90,
        "coin collecting": 90,
        "model building": 180,
        "train modeling": 240,
        "diorama building": 180
    ]

    
    func estimateTime(for task: String) -> Int {
        let lowercasedTask = task.lowercased()
        for (keyword, minutes) in timeEstimates {
            if lowercasedTask.contains(keyword) {
                return minutes
            }
        }
        // Default time if no keyword matches
        return 0
    }
}
